default: &default
  adapter: <%= ENV['DATABASE_ADAPTER'] || 'mysql2' %>
  encoding: utf8
  pool: 5
  timeout: 5000
  host: <%= ENV['DATA_MYSQL_HOST'] || 'localhost' %>
  username: <%= ENV['DATA_MYSQL_USER'] || 'root' %>
  password: <%= ENV['DATA_MYSQL_PASS'] || 'admin' %>

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
