default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  host: <%= ENV['DATA_MYSQL_HOST'] %>
  username: <%= ENV['DATA_MYSQL_USER'] %>
  password: <%= ENV['DATA_MYSQL_PASS'] %>

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>

