default: &default
  adapter: <%= ENV['DATABASE_ADAPTER'] || 'mysql2' %>
  encoding: utf8
  pool: 5
  timeout: 5000
  host: <%= ENV['DATA_MYSQL_HOST'] %>
  username: <%= ENV['DATA_MYSQL_USER'] %>
  password: <%= ENV['DATA_MYSQL_PASS'] %>

development:
  <<: *default
  database: gonano

test:
  <<: *default
  database: test

production:
  <<: *default
  database: gonano
